### ISSUE TITLE
containers_api : killalljobs

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [g8os/grid#121] opened 2017-04-24 14:38 UTC
## Reproduce 
```REST
delete http://{{url}}/nodes/:node_name/containers/:container_id/jobs
```
kill all jobs in container api always returns a 500.

## Response 500
{
  "error": "Error getting service 0"
}

**Comment by serboctor** [comment] 2017-04-26 09:45
I couldn't reproduce this exact error. However, I got another error which I fixed. The fix for this requires updates the go-client.

**Closed** 2017-04-26 12:00 UTC
Labels: state_verification, type_bug
